"""add voices column to azure_credentials

Revision ID: 0044117385a8
Revises: 0f97a59ea388
Create Date: 2025-09-21 21:13:52.740177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0044117385a8'
down_revision: Union[str, Sequence[str], None] = '0f97a59ea388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azure_credentials', sa.Column('voices', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False), schema='spellcast')
    op.add_column('azure_credentials', sa.Column('shared', sa.Boolean(), nullable=True), schema='spellcast')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('azure_credentials', 'shared', schema='spellcast')
    op.drop_column('azure_credentials', 'voices', schema='spellcast')
    # ### end Alembic commands ###
