"""migracion current_credential

Revision ID: 143f8d04cd2b
Revises: 0044117385a8
Create Date: 2025-09-30 21:28:35.836687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143f8d04cd2b'
down_revision: Union[str, Sequence[str], None] = '0044117385a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscription', sa.Column('current_credential', sa.UUID(), nullable=True), schema='spellcast')
    op.create_foreign_key(None, 'user_subscription', 'azure_credentials', ['current_credential'], ['id'], source_schema='spellcast', referent_schema='spellcast')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_subscription', schema='spellcast', type_='foreignkey')
    op.drop_column('user_subscription', 'current_credential', schema='spellcast')
    # ### end Alembic commands ###
