"""create_credentials_multi_provider_table

Revision ID: bdc3fe32fe29
Revises: 4056053934a4
Create Date: 2026-07-26 19:44:56.946627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdc3fe32fe29'
down_revision: Union[str, Sequence[str], None] = '4056053934a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('voices', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('shared', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='spellcast'
    )
    #op.drop_table('azure_credentials', schema='spellcast')
    #op.drop_constraint(op.f('user_subscription_current_credential_fkey'), 'user_subscription', schema='spellcast', type_='foreignkey')
    #op.create_foreign_key(None, 'user_subscription', 'credential', ['current_credential'], ['id'], source_schema='spellcast', referent_schema='spellcast')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_subscription', schema='spellcast', type_='foreignkey')
    op.create_foreign_key(op.f('user_subscription_current_credential_fkey'), 'user_subscription', 'azure_credentials', ['current_credential'], ['id'], source_schema='spellcast', referent_schema='spellcast')
    op.create_table('azure_credentials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('azure_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('voices', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('shared', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('azure_credentials_pkey')),
    schema='spellcast'
    )
    op.drop_table('credential', schema='spellcast')
    # ### end Alembic commands ###
